core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path("users/",include('users.urls')),
    path("document/", include('products.urls')),
    path('users/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from .views import IndexView, categoryFilter, articleFilter

app_name = 'main' #=> Asosiy app
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category/<int:pk>',categoryFilter, name='category_list'),
    path('science/<int:pk>',articleFilter, name='article_list'),
    
]

products/urls.py
from django.urls import path
from .views import new_product, product_detail, product_update, product_delate

app_name = 'products'
urlpatterns = [
    path('new', new_product, name='new'),
    path('<int:pk>/detail', product_detail, name='detail'),
    path('<int:pk>/update', product_update, name='update'),
    path('<int:pk>/delate', product_delate, name='delate'),
]

users/urls.py
from django.urls import path
from .views import SignupView, ProfileView, UpdateProfileView

app_name = 'users'
urlpatterns = [
    path('signup/',SignupView.as_view(), name='signup'),
    path('profile/<str:username>',ProfileView.as_view(), name='profile'),
    path('update',UpdateProfileView.as_view(), name='update'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <title>Document</title>
</head>
<body>
    <div>
        <nav class="navbar-top">
            <div class="container">
                <div class="navbar-box-top">
                    {% if request.user.is_authenticated %}
                        <a href="{% url "products:new" %}">Fayl yuklash</a>
                        <a href="{% url "users:profile" request.user  %}">Profil</a>
                        <a href="{% url "logout" %}">Log out</a>
                    {% else %}
                        <a href="{% url "login" %}">kirish</a>
                        <a href="{% url "users:signup" %}">Ro'yxatdan o'tish</a>
                    {% endif %}
                </div>
            </div>
            <div class="bg-2">
                <div class="container">
                    <div class="navbar-box-bottom">
                        <h2 class="link-h2"><a href='{% url "main:index" %}' style='text-decoration:none; color:#1a1a1a;'>Docx</a></h2>
                        <ul>
                            {% for i in category %}
                                {% if forloop.counter <= 2 %}
                                    <li><a href="{% url 'main:category_list' i.pk %}">{{ i.name }}</a></li>
                                {% endif %}
                            {% endfor %}
                            <li class="vse"><a href="#">Boshqalar</a>
                                <div class="block-p">
                                    <ul class="ul-2">
        
                                        {% for i in category %}
                                            <li class="li-2"><a class="a2" href="{% url 'main:category_list' i.pk %}">{{ i.name }}</a></li>
                                        {% endfor %}
        
                                    </ul>
                                </div>
                            </li>
                        
                        </ul>
                    </div>
                </div>
            </div>
                
        </nav>
    </div>
    

    <div>{% block content %}{% endblock content %}</div>
    
    
    <div>
        <footer>
            <div class="container p-3 d-flex justify-content-between">
                <div class="left">
                    <h6>&copy; Copyright 2023-2024. Created by IT-Politech Group</h6>
                </div>
                <div class="right">
                    <ul>
                        <li><a href="#">Balansdan chiqarish bo'yicha ko'rsatmalar</a></li>
                        <li><a href="#">Biz bilan aloqa</a></li>
                        <li><a href="#">Saytdan foydalanish yuriqnomasi</a></li>
                        <li><a href="#">Fayl yuklash yuriqnomasi</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>
    <script src="{% static "js/bootstrap.js" %}"></script>
    <script src="{% static "js/jquery.js" %}"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    
    <section class="bg-img">
        <div class="container cont-nav-center">
            <h1>Hujjatlarni yuklang va pul ishlang</h1>
            <p>Hujjatlarni sotish uchun sayt</p>
            <div class="nav-cont-line"></div>
            <div class="cont-nav-center-box">
                <div class="search-input">
                    <input type="text" placeholder="qidirish">
                    <a href="#"><img src="{% static "img/Remove-bg.ai_1721827232078.png" %}"></a>
                </div>
            </div>
                
        </div>
    </section>
 
    <section class="categorys">
        <div class="container">
            <ul>
                <li><a href="{% url "main:index" %}" class='active'>Hammasi</a></li>
                {% for i in science %}
                    <li><a href="{% url "main:article_list" i.pk %}">{{ i.name }}</a></li>
                {% endfor %}

            </ul>
        </div>
    </section>
    
    <section>
        <div class="container d-flex flex-wrap mb-3">
           
            {% for product in products %}
            {% if forloop.counter <= 16 %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name|truncatewords:7 }}</h5>
                    <div class="text-name">
                        <p class="p1">Muallif: {{ product.Author }} </p>
                        <p class="p2">Bo'lim: {{ product.category }} </p>
                    </div>
                    <div class="text-data">
                        <p class="p1">Yuklab olishlar soni: 0 </p>
                        <p class="p2">Yuklangan Sana: {{ product.created }} </p>
                    </div>                    
                    <div class="card-line"></div>
                    <div class="text-btn">
                        <a href="{% url "products:detail" product.pk %}">Ko'rish</a>
                        {% comment %} <h4>{{ product.price }} UZS</h4> {% endcomment %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
           

        
  
        </div>
    </section>

    <div class="container">
        <nav aria-label="Page navigation example ">
            <ul class="pagination justify-content-center">
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
    </div>

{% endblock content %}


    

templates/product_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<section class="bg-color mb-4">
    <div class="container cont-nav-center">
        <h1>Dakument Yaratish</h1>    
    </div>
</section>

<section>
    <div class="container cont-nav-center-form">
        <form method="post" enctype="multipart/form-data">
        
            {% csrf_token %}
            {{ form|crispy }}            

            <button type='submit' class="btn btn-outline-success">Saqlash</button>
        </form>  
    </div>
</section>

{% endblock content %}

templates/product_delate.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <form method='post' class='signup-form'>{% csrf_token %}
        
        <h2>{{ product.name }} O'chirish</h2>
        {{ form|crispy }}
        
        <button type="submit" class="btn btn-danger">O'chirish</button>
    </form>
    
    
</div>

{% endblock content %}

templates/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="container p-5 mb-5">
    <section>
        <div class="container cont-user">
            <div class="row">
              
                <div class="col-md-4 card p-5">
                    <h3 class="mb-4">Dokument malumoti</h3>
                    <div class="d-flex justify-content-between">
                        <div><span>Narxi:</span></div>
                        <div> {{ product.price }} UZS</div>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <div><span>Hajmi:</span></div>
                        <div> {{ product.file.size }} KB </div>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <div><span>Yuklash sanasi:</span></div>
                        <div>{{ product.created }}</div>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <div><span>Bo'lim:</span></div>
                        <div> {{ product.category }} </div>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <div><span>Fan:</span></div>
                        <div>{{ product.categoryScience }}</div>
                    </div>
                
                    <hr>
                    <div class="d-flex justify-content-between">
                        <div><span>Sotuvchi:</span></div>
                        <div>{{ product.Author }}</div>
                    </div>        
                    <hr>
                    <div class="d-flex justify-content-between">
  
                        <a href="{% url "products:update" product.pk %}" class='btn btn-success'>Taxrirlash</a>
                        <a href="{% url "products:delate" product.pk %}" class='btn btn-danger'>O'chirish</a>    
                        
                    </div>

                </div>

                <div class="col">
                    <div class="card" style="width: 100% !important;">
                        <center><h4>Ommaviy axborot rivojlantirishga ta’siri vositalarning bola ma’naviyatini rivojlantirishga ta’siri</h4></center>
                    </div>
                   
                   
                    <div class="card" style="width: 100% !important;">
                        <div class="d-flex justify-content-around">
                            <a href='' class='btn btn-success'>Click orqali</a>
                            <a href='' class='btn btn-success'>Payme orqali</a>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </section>


    
</div>

    
 



{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="container p-5 mb-5">
    <h3 class='mt-2 mb-5'>Profil ma'lumotlari</h3>

    <div class="row mt-5">
        <div class="col-sm-3"><strong>To'liq ism</strong></div>
        <div class="col-sm-9">{{ customuser.first_name }}</div>
    </div>
    <hr>

    <div class="row">
        <div class="col-sm-3"><strong>Login</strong></div>
        <div class="col-sm-9">{{ customuser.username }}</div>
    </div>
    <hr>

    <div class="row">
        <div class="col-sm-3"><strong>Email</strong></div>
        <div class="col-sm-9"> {{ customuser.email }} </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-sm-3"><strong>Nomer</strong></div>
        <div class="col-sm-9"> {{ customuser.phone_number }} </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-sm-9">
            {% if customuser == request.user %}
            <a href="{% url "users:update"  %}" class='btn btn-success'>Fodalanuvchi profilini Taxrirlash</a>
            <a href="{% url "password_change" %}" class='btn btn-danger'>Fodalanuvchi Parolini o'zgartirish</a>
            {% endif %}
        </div>
    </div>
    <hr>


    
</div>

    
 



{% endblock content %}

templates/profile_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <form method='post' class="m-5">{% csrf_token %}  
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Saqlash</button>    
  </form>

</div>

{% endblock content %}